// Command fetch-provider-rates is the build-time adapter for kyber's pricing
// data (kyber#487). It fetches LiteLLM's public model_prices_and_context_window
// .json (MIT), projects it to kyber's per-MTok ProviderRates shape via
// metrics.ProjectLiteLLM (provider filter + sanity bounds), and writes the
// vendored dataset + a freshness stamp the chart renders into the
// kyber-provider-rates ConfigMap.
//
// It runs in CI (the weekly refresh-bot workflow opens a PR with the
// regenerated dataset) — never at runtime. The third party stays out of the
// control-plane request path and behind human review of the resulting diff.
//
// Usage:
//
//	fetch-provider-rates \
//	  -url https://raw.githubusercontent.com/BerriAI/litellm/<sha>/model_prices_and_context_window.json \
//	  -commit <sha> \
//	  -out deploy/helm/kyber/files/provider-rates.generated.yaml \
//	  -meta deploy/helm/kyber/files/provider-rates.generated.meta \
//	  -now 2026-06-07T15:00:00Z
//
// -in <file> reads a local feed copy instead of fetching (offline/testing).
// -now defaults to the current UTC time; pass it for reproducible output.
package main

import (
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/matty-v/kyber/pkg/metrics"
)

// providersWeSurface gates the projection by litellm_provider. A provider-scoped
// filter (not a per-model hand list) keeps the ConfigMap small while staying
// "no manually-maintained model data" — we curate providers, never prices.
var providersWeSurface = map[string]bool{
	"anthropic": true,
	"openai":    true,
}

// sanity bounds in USD per million tokens: reject non-positive or absurd values
// (e.g. an unscaled per-token cost) so a malformed feed can't ship a
// confidently-wrong price — it falls to the unpriced badge instead.
var bounds = metrics.RateBounds{MinPerMTok: 0, MaxPerMTok: 10_000}

func main() {
	url := flag.String("url", "", "raw URL of the LiteLLM model-prices JSON (pin to a commit sha)")
	in := flag.String("in", "", "read feed from this local file instead of fetching -url")
	commit := flag.String("commit", "", "upstream commit sha the feed was pinned to (recorded in the meta stamp)")
	out := flag.String("out", "deploy/helm/kyber/files/provider-rates.generated.yaml", "vendored dataset output path")
	metaPath := flag.String("meta", "deploy/helm/kyber/files/provider-rates.generated.meta", "freshness stamp output path")
	now := flag.String("now", "", "RFC3339 fetch timestamp (default: current UTC)")
	flag.Parse()

	raw, err := loadFeed(*url, *in)
	if err != nil {
		fail(err)
	}

	table, rejected, err := metrics.ProjectLiteLLM(raw, providersWeSurface, bounds)
	if err != nil {
		fail(err)
	}
	if len(table) == 0 {
		fail(fmt.Errorf("projection produced 0 models — feed empty or all rejected (refusing to write an empty dataset)"))
	}

	fetchedAt := *now
	if fetchedAt == "" {
		fetchedAt = time.Now().UTC().Format(time.RFC3339)
	}

	header := fmt.Sprintf(`# Provider token rates — USD per 1 million tokens.
# GENERATED by cmd/fetch-provider-rates — DO NOT EDIT BY HAND (kyber#487).
# Source: LiteLLM model_prices_and_context_window.json (MIT license),
#   github.com/BerriAI/litellm — projected to kyber ProviderRates at build time.
# Upstream commit: %s
# Fetched: %s
# Models: %d (providers: %s) | rejected by sanity bounds: %d
`, dash(*commit), fetchedAt, len(table), providerList(), len(rejected))

	dataset, err := metrics.RenderRatesYAML(table, header)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(*out, dataset, 0o644); err != nil {
		fail(fmt.Errorf("write dataset %s: %w", *out, err))
	}

	meta := fmt.Sprintf(`source: litellm
upstream_repo: BerriAI/litellm
upstream_file: model_prices_and_context_window.json
upstream_commit: %s
fetched_at: %s
model_count: %d
rejected_count: %d
`, dash(*commit), fetchedAt, len(table), len(rejected))
	if err := os.WriteFile(*metaPath, []byte(meta), 0o644); err != nil {
		fail(fmt.Errorf("write meta %s: %w", *metaPath, err))
	}

	fmt.Printf("fetch-provider-rates: wrote %d models to %s (rejected %d), stamp %s\n",
		len(table), *out, len(rejected), *metaPath)
	if len(rejected) > 0 {
		fmt.Printf("fetch-provider-rates: rejected ids: %s\n", strings.Join(rejected, ", "))
	}
}

func loadFeed(url, in string) ([]byte, error) {
	if in != "" {
		return os.ReadFile(in)
	}
	if url == "" {
		return nil, fmt.Errorf("one of -url or -in is required")
	}
	resp, err := http.Get(url) //nolint:gosec // build-time fetch of a pinned public URL
	if err != nil {
		return nil, fmt.Errorf("fetch %s: %w", url, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("fetch %s: HTTP %d", url, resp.StatusCode)
	}
	return io.ReadAll(resp.Body)
}

func providerList() string {
	ps := make([]string, 0, len(providersWeSurface))
	for p := range providersWeSurface {
		ps = append(ps, p)
	}
	sort.Strings(ps)
	return strings.Join(ps, ", ")
}

func dash(s string) string {
	if s == "" {
		return "(unpinned)"
	}
	return s
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "fetch-provider-rates: %v\n", err)
	os.Exit(1)
}
