{{- if .Values.preview.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kyber.fullname" . }}-control-plane-preview
  namespace: {{ include "kyber.namespace" . }}
  labels:
    {{- include "kyber.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  annotations:
    cloudflare-tunnel-ingress-controller.strrl.dev/backend-protocol: http
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: {{ .Values.preview.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kyber.fullname" . }}-control-plane
                port:
                  name: http
{{- end }}
