apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kyber.fullname" . }}-control-plane
  namespace: {{ include "kyber.namespace" . }}
  labels:
    {{- include "kyber.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
