apiVersion: v1
kind: Service
metadata:
  name: {{ include "kyber.fullname" . }}-control-plane
  namespace: {{ include "kyber.namespace" . }}
  labels:
    {{- include "kyber.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "kyber.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
    - name: internal
      port: {{ .Values.api.service.internalPort }}
      targetPort: internal
      protocol: TCP
    - name: metrics
      port: {{ .Values.api.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
