//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityStatus) DeepCopyInto(out *ActivityStatus) {
	*out = *in
	if in.LastHeartbeatAt != nil {
		in, out := &in.LastHeartbeatAt, &out.LastHeartbeatAt
		*out = (*in).DeepCopy()
	}
	if in.LastActivityAt != nil {
		in, out := &in.LastActivityAt, &out.LastActivityAt
		*out = (*in).DeepCopy()
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(AgentResourceUsage)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityStatus.
func (in *ActivityStatus) DeepCopy() *ActivityStatus {
	if in == nil {
		return nil
	}
	out := new(ActivityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Agent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannels) DeepCopyInto(out *AgentChannels) {
	*out = *in
	if in.Discord != nil {
		in, out := &in.Discord, &out.Discord
		*out = new(AgentDiscordChannel)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannels.
func (in *AgentChannels) DeepCopy() *AgentChannels {
	if in == nil {
		return nil
	}
	out := new(AgentChannels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDiscordChannel) DeepCopyInto(out *AgentDiscordChannel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDiscordChannel.
func (in *AgentDiscordChannel) DeepCopy() *AgentDiscordChannel {
	if in == nil {
		return nil
	}
	out := new(AgentDiscordChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIdentity) DeepCopyInto(out *AgentIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIdentity.
func (in *AgentIdentity) DeepCopy() *AgentIdentity {
	if in == nil {
		return nil
	}
	out := new(AgentIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIdentityRepo) DeepCopyInto(out *AgentIdentityRepo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIdentityRepo.
func (in *AgentIdentityRepo) DeepCopy() *AgentIdentityRepo {
	if in == nil {
		return nil
	}
	out := new(AgentIdentityRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIdentityRepoStatus) DeepCopyInto(out *AgentIdentityRepoStatus) {
	*out = *in
	if in.TokenExpiresAt != nil {
		in, out := &in.TokenExpiresAt, &out.TokenExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.LastMinted != nil {
		in, out := &in.LastMinted, &out.LastMinted
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIdentityRepoStatus.
func (in *AgentIdentityRepoStatus) DeepCopy() *AgentIdentityRepoStatus {
	if in == nil {
		return nil
	}
	out := new(AgentIdentityRepoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentInboundBinding) DeepCopyInto(out *AgentInboundBinding) {
	*out = *in
	if in.MatchEvents != nil {
		in, out := &in.MatchEvents, &out.MatchEvents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]AgentInboundFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]AgentInboundField, len(*in))
		copy(*out, *in)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(AgentInboundLimits)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentInboundBinding.
func (in *AgentInboundBinding) DeepCopy() *AgentInboundBinding {
	if in == nil {
		return nil
	}
	out := new(AgentInboundBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentInboundField) DeepCopyInto(out *AgentInboundField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentInboundField.
func (in *AgentInboundField) DeepCopy() *AgentInboundField {
	if in == nil {
		return nil
	}
	out := new(AgentInboundField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentInboundFilter) DeepCopyInto(out *AgentInboundFilter) {
	*out = *in
	if in.In != nil {
		in, out := &in.In, &out.In
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentInboundFilter.
func (in *AgentInboundFilter) DeepCopy() *AgentInboundFilter {
	if in == nil {
		return nil
	}
	out := new(AgentInboundFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentInboundLimits) DeepCopyInto(out *AgentInboundLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentInboundLimits.
func (in *AgentInboundLimits) DeepCopy() *AgentInboundLimits {
	if in == nil {
		return nil
	}
	out := new(AgentInboundLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentInboundRun) DeepCopyInto(out *AgentInboundRun) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentInboundRun.
func (in *AgentInboundRun) DeepCopy() *AgentInboundRun {
	if in == nil {
		return nil
	}
	out := new(AgentInboundRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentJob) DeepCopyInto(out *AgentJob) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentJob.
func (in *AgentJob) DeepCopy() *AgentJob {
	if in == nil {
		return nil
	}
	out := new(AgentJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentJobRun) DeepCopyInto(out *AgentJobRun) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentJobRun.
func (in *AgentJobRun) DeepCopy() *AgentJobRun {
	if in == nil {
		return nil
	}
	out := new(AgentJobRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Agent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentList.
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPublicCapabilities) DeepCopyInto(out *AgentPublicCapabilities) {
	*out = *in
	out.Identity = in.Identity
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]AgentPublicCapability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPublicCapabilities.
func (in *AgentPublicCapabilities) DeepCopy() *AgentPublicCapabilities {
	if in == nil {
		return nil
	}
	out := new(AgentPublicCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPublicCapabilitiesStatus) DeepCopyInto(out *AgentPublicCapabilitiesStatus) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]AgentPublicCapabilityAvailability, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPublicCapabilitiesStatus.
func (in *AgentPublicCapabilitiesStatus) DeepCopy() *AgentPublicCapabilitiesStatus {
	if in == nil {
		return nil
	}
	out := new(AgentPublicCapabilitiesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPublicCapability) DeepCopyInto(out *AgentPublicCapability) {
	*out = *in
	if in.InputModes != nil {
		in, out := &in.InputModes, &out.InputModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OutputModes != nil {
		in, out := &in.OutputModes, &out.OutputModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TaskFeatures != nil {
		in, out := &in.TaskFeatures, &out.TaskFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = new(AgentPublicCapabilityEvidence)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPublicCapability.
func (in *AgentPublicCapability) DeepCopy() *AgentPublicCapability {
	if in == nil {
		return nil
	}
	out := new(AgentPublicCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPublicCapabilityAvailability) DeepCopyInto(out *AgentPublicCapabilityAvailability) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPublicCapabilityAvailability.
func (in *AgentPublicCapabilityAvailability) DeepCopy() *AgentPublicCapabilityAvailability {
	if in == nil {
		return nil
	}
	out := new(AgentPublicCapabilityAvailability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPublicCapabilityEvidence) DeepCopyInto(out *AgentPublicCapabilityEvidence) {
	*out = *in
	if in.RequiredSkills != nil {
		in, out := &in.RequiredSkills, &out.RequiredSkills
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredConnectors != nil {
		in, out := &in.RequiredConnectors, &out.RequiredConnectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredPlatformFeatures != nil {
		in, out := &in.RequiredPlatformFeatures, &out.RequiredPlatformFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RuntimeAdapters != nil {
		in, out := &in.RuntimeAdapters, &out.RuntimeAdapters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPublicCapabilityEvidence.
func (in *AgentPublicCapabilityEvidence) DeepCopy() *AgentPublicCapabilityEvidence {
	if in == nil {
		return nil
	}
	out := new(AgentPublicCapabilityEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPublicCapabilityIdentity) DeepCopyInto(out *AgentPublicCapabilityIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPublicCapabilityIdentity.
func (in *AgentPublicCapabilityIdentity) DeepCopy() *AgentPublicCapabilityIdentity {
	if in == nil {
		return nil
	}
	out := new(AgentPublicCapabilityIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentResourceUsage) DeepCopyInto(out *AgentResourceUsage) {
	*out = *in
	in.SampledAt.DeepCopyInto(&out.SampledAt)
	if in.CPULimitMillicores != nil {
		in, out := &in.CPULimitMillicores, &out.CPULimitMillicores
		*out = new(int64)
		**out = **in
	}
	if in.MemoryLimitBytes != nil {
		in, out := &in.MemoryLimitBytes, &out.MemoryLimitBytes
		*out = new(int64)
		**out = **in
	}
	if in.DiskUsedSampledAt != nil {
		in, out := &in.DiskUsedSampledAt, &out.DiskUsedSampledAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentResourceUsage.
func (in *AgentResourceUsage) DeepCopy() *AgentResourceUsage {
	if in == nil {
		return nil
	}
	out := new(AgentResourceUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentResources) DeepCopyInto(out *AgentResources) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
	out.Disk = in.Disk.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentResources.
func (in *AgentResources) DeepCopy() *AgentResources {
	if in == nil {
		return nil
	}
	out := new(AgentResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeStatus) DeepCopyInto(out *AgentRuntimeStatus) {
	*out = *in
	if in.Usable != nil {
		in, out := &in.Usable, &out.Usable
		*out = new(bool)
		**out = **in
	}
	if in.InstalledAt != nil {
		in, out := &in.InstalledAt, &out.InstalledAt
		*out = (*in).DeepCopy()
	}
	if in.RequestedSatisfied != nil {
		in, out := &in.RequestedSatisfied, &out.RequestedSatisfied
		*out = new(bool)
		**out = **in
	}
	if in.ModelSupported != nil {
		in, out := &in.ModelSupported, &out.ModelSupported
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeStatus.
func (in *AgentRuntimeStatus) DeepCopy() *AgentRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSchedulingStatus) DeepCopyInto(out *AgentSchedulingStatus) {
	*out = *in
	if in.FirstObservedAt != nil {
		in, out := &in.FirstObservedAt, &out.FirstObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSchedulingStatus.
func (in *AgentSchedulingStatus) DeepCopy() *AgentSchedulingStatus {
	if in == nil {
		return nil
	}
	out := new(AgentSchedulingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSecrets) DeepCopyInto(out *AgentSecrets) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSecrets.
func (in *AgentSecrets) DeepCopy() *AgentSecrets {
	if in == nil {
		return nil
	}
	out := new(AgentSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.PublicCapabilities != nil {
		in, out := &in.PublicCapabilities, &out.PublicCapabilities
		*out = new(AgentPublicCapabilities)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	out.Identity = in.Identity
	out.IdentityRepo = in.IdentityRepo
	out.Secrets = in.Secrets
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]AgentJob, len(*in))
		copy(*out, *in)
	}
	if in.InboundBindings != nil {
		in, out := &in.InboundBindings, &out.InboundBindings
		*out = make([]AgentInboundBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = new(AgentChannels)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.LastTransition != nil {
		in, out := &in.LastTransition, &out.LastTransition
		*out = (*in).DeepCopy()
	}
	in.IdentityRepo.DeepCopyInto(&out.IdentityRepo)
	in.Runtime.DeepCopyInto(&out.Runtime)
	if in.PublicCapabilities != nil {
		in, out := &in.PublicCapabilities, &out.PublicCapabilities
		*out = new(AgentPublicCapabilitiesStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]AgentJobRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InboundRuns != nil {
		in, out := &in.InboundRuns, &out.InboundRuns
		*out = make([]AgentInboundRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Scheduling != nil {
		in, out := &in.Scheduling, &out.Scheduling
		*out = new(AgentSchedulingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Activity != nil {
		in, out := &in.Activity, &out.Activity
		*out = new(ActivityStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastKernelOOMKillAt != nil {
		in, out := &in.LastKernelOOMKillAt, &out.LastKernelOOMKillAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Machine) DeepCopyInto(out *Machine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Machine.
func (in *Machine) DeepCopy() *Machine {
	if in == nil {
		return nil
	}
	out := new(Machine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Machine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineCapacity) DeepCopyInto(out *MachineCapacity) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
	out.EphemeralStorage = in.EphemeralStorage.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineCapacity.
func (in *MachineCapacity) DeepCopy() *MachineCapacity {
	if in == nil {
		return nil
	}
	out := new(MachineCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineList) DeepCopyInto(out *MachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Machine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineList.
func (in *MachineList) DeepCopy() *MachineList {
	if in == nil {
		return nil
	}
	out := new(MachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineSpec) DeepCopyInto(out *MachineSpec) {
	*out = *in
	in.Capacity.DeepCopyInto(&out.Capacity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineSpec.
func (in *MachineSpec) DeepCopy() *MachineSpec {
	if in == nil {
		return nil
	}
	out := new(MachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineStatus) DeepCopyInto(out *MachineStatus) {
	*out = *in
	if in.FallbackSince != nil {
		in, out := &in.FallbackSince, &out.FallbackSince
		*out = (*in).DeepCopy()
	}
	if in.CostOptimizedUnavailableSince != nil {
		in, out := &in.CostOptimizedUnavailableSince, &out.CostOptimizedUnavailableSince
		*out = (*in).DeepCopy()
	}
	if in.CostOptimizedRetrySince != nil {
		in, out := &in.CostOptimizedRetrySince, &out.CostOptimizedRetrySince
		*out = (*in).DeepCopy()
	}
	if in.ResolvedProfile != nil {
		in, out := &in.ResolvedProfile, &out.ResolvedProfile
		*out = new(ResolvedMachineProfile)
		(*in).DeepCopyInto(*out)
	}
	if in.LastHealthCheck != nil {
		in, out := &in.LastHealthCheck, &out.LastHealthCheck
		*out = (*in).DeepCopy()
	}
	if in.LastTransition != nil {
		in, out := &in.LastTransition, &out.LastTransition
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObservedCapacity != nil {
		in, out := &in.ObservedCapacity, &out.ObservedCapacity
		*out = new(MachineCapacity)
		(*in).DeepCopyInto(*out)
	}
	if in.AssignableCapacity != nil {
		in, out := &in.AssignableCapacity, &out.AssignableCapacity
		*out = new(MachineCapacity)
		(*in).DeepCopyInto(*out)
	}
	if in.AvailableCapacity != nil {
		in, out := &in.AvailableCapacity, &out.AvailableCapacity
		*out = new(MachineCapacity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineStatus.
func (in *MachineStatus) DeepCopy() *MachineStatus {
	if in == nil {
		return nil
	}
	out := new(MachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedMachineProfile) DeepCopyInto(out *ResolvedMachineProfile) {
	*out = *in
	in.Capacity.DeepCopyInto(&out.Capacity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedMachineProfile.
func (in *ResolvedMachineProfile) DeepCopy() *ResolvedMachineProfile {
	if in == nil {
		return nil
	}
	out := new(ResolvedMachineProfile)
	in.DeepCopyInto(out)
	return out
}
